image: arthurchaloin/epitech-fedora:latest

build:
    script:
        - mkdir build
        - cd build
        - cmake ..
        - cmake --build .

test:
    script:
        - mkdir build
        - cd build
        - cmake ..
        - cmake --build .
        - ./tests-engine
        - ../coverage.sh
