# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arbona/work/tek/indie

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arbona/work/tek/indie

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arbona/work/tek/indie/CMakeFiles /home/arbona/work/tek/indie/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arbona/work/tek/indie/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/build
.PHONY : engine/fast

#=============================================================================
# Target rules for targets named worms

# Build rule for target.
worms: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 worms
.PHONY : worms

# fast build rule for target.
worms/fast:
	$(MAKE) -f CMakeFiles/worms.dir/build.make CMakeFiles/worms.dir/build
.PHONY : worms/fast

#=============================================================================
# Target rules for targets named worms-server

# Build rule for target.
worms-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 worms-server
.PHONY : worms-server

# fast build rule for target.
worms-server/fast:
	$(MAKE) -f CMakeFiles/worms-server.dir/build.make CMakeFiles/worms-server.dir/build
.PHONY : worms-server/fast

#=============================================================================
# Target rules for targets named tests-engine

# Build rule for target.
tests-engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests-engine
.PHONY : tests-engine

# fast build rule for target.
tests-engine/fast:
	$(MAKE) -f tests/CMakeFiles/tests-engine.dir/build.make tests/CMakeFiles/tests-engine.dir/build
.PHONY : tests-engine/fast

src/client.o: src/client.cpp.o

.PHONY : src/client.o

# target to build an object file
src/client.cpp.o:
	$(MAKE) -f CMakeFiles/worms.dir/build.make CMakeFiles/worms.dir/src/client.cpp.o
.PHONY : src/client.cpp.o

src/client.i: src/client.cpp.i

.PHONY : src/client.i

# target to preprocess a source file
src/client.cpp.i:
	$(MAKE) -f CMakeFiles/worms.dir/build.make CMakeFiles/worms.dir/src/client.cpp.i
.PHONY : src/client.cpp.i

src/client.s: src/client.cpp.s

.PHONY : src/client.s

# target to generate assembly for a file
src/client.cpp.s:
	$(MAKE) -f CMakeFiles/worms.dir/build.make CMakeFiles/worms.dir/src/client.cpp.s
.PHONY : src/client.cpp.s

src/engine/components/CameraComponent.o: src/engine/components/CameraComponent.cpp.o

.PHONY : src/engine/components/CameraComponent.o

# target to build an object file
src/engine/components/CameraComponent.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/components/CameraComponent.cpp.o
.PHONY : src/engine/components/CameraComponent.cpp.o

src/engine/components/CameraComponent.i: src/engine/components/CameraComponent.cpp.i

.PHONY : src/engine/components/CameraComponent.i

# target to preprocess a source file
src/engine/components/CameraComponent.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/components/CameraComponent.cpp.i
.PHONY : src/engine/components/CameraComponent.cpp.i

src/engine/components/CameraComponent.s: src/engine/components/CameraComponent.cpp.s

.PHONY : src/engine/components/CameraComponent.s

# target to generate assembly for a file
src/engine/components/CameraComponent.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/components/CameraComponent.cpp.s
.PHONY : src/engine/components/CameraComponent.cpp.s

src/engine/components/ComponentPoolEvent.o: src/engine/components/ComponentPoolEvent.cpp.o

.PHONY : src/engine/components/ComponentPoolEvent.o

# target to build an object file
src/engine/components/ComponentPoolEvent.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/components/ComponentPoolEvent.cpp.o
.PHONY : src/engine/components/ComponentPoolEvent.cpp.o

src/engine/components/ComponentPoolEvent.i: src/engine/components/ComponentPoolEvent.cpp.i

.PHONY : src/engine/components/ComponentPoolEvent.i

# target to preprocess a source file
src/engine/components/ComponentPoolEvent.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/components/ComponentPoolEvent.cpp.i
.PHONY : src/engine/components/ComponentPoolEvent.cpp.i

src/engine/components/ComponentPoolEvent.s: src/engine/components/ComponentPoolEvent.cpp.s

.PHONY : src/engine/components/ComponentPoolEvent.s

# target to generate assembly for a file
src/engine/components/ComponentPoolEvent.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/components/ComponentPoolEvent.cpp.s
.PHONY : src/engine/components/ComponentPoolEvent.cpp.s

src/engine/components/HitboxComponent.o: src/engine/components/HitboxComponent.cpp.o

.PHONY : src/engine/components/HitboxComponent.o

# target to build an object file
src/engine/components/HitboxComponent.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/components/HitboxComponent.cpp.o
.PHONY : src/engine/components/HitboxComponent.cpp.o

src/engine/components/HitboxComponent.i: src/engine/components/HitboxComponent.cpp.i

.PHONY : src/engine/components/HitboxComponent.i

# target to preprocess a source file
src/engine/components/HitboxComponent.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/components/HitboxComponent.cpp.i
.PHONY : src/engine/components/HitboxComponent.cpp.i

src/engine/components/HitboxComponent.s: src/engine/components/HitboxComponent.cpp.s

.PHONY : src/engine/components/HitboxComponent.s

# target to generate assembly for a file
src/engine/components/HitboxComponent.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/components/HitboxComponent.cpp.s
.PHONY : src/engine/components/HitboxComponent.cpp.s

src/engine/components/IrrlichtComponent.o: src/engine/components/IrrlichtComponent.cpp.o

.PHONY : src/engine/components/IrrlichtComponent.o

# target to build an object file
src/engine/components/IrrlichtComponent.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/components/IrrlichtComponent.cpp.o
.PHONY : src/engine/components/IrrlichtComponent.cpp.o

src/engine/components/IrrlichtComponent.i: src/engine/components/IrrlichtComponent.cpp.i

.PHONY : src/engine/components/IrrlichtComponent.i

# target to preprocess a source file
src/engine/components/IrrlichtComponent.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/components/IrrlichtComponent.cpp.i
.PHONY : src/engine/components/IrrlichtComponent.cpp.i

src/engine/components/IrrlichtComponent.s: src/engine/components/IrrlichtComponent.cpp.s

.PHONY : src/engine/components/IrrlichtComponent.s

# target to generate assembly for a file
src/engine/components/IrrlichtComponent.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/components/IrrlichtComponent.cpp.s
.PHONY : src/engine/components/IrrlichtComponent.cpp.s

src/engine/components/LightComponent.o: src/engine/components/LightComponent.cpp.o

.PHONY : src/engine/components/LightComponent.o

# target to build an object file
src/engine/components/LightComponent.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/components/LightComponent.cpp.o
.PHONY : src/engine/components/LightComponent.cpp.o

src/engine/components/LightComponent.i: src/engine/components/LightComponent.cpp.i

.PHONY : src/engine/components/LightComponent.i

# target to preprocess a source file
src/engine/components/LightComponent.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/components/LightComponent.cpp.i
.PHONY : src/engine/components/LightComponent.cpp.i

src/engine/components/LightComponent.s: src/engine/components/LightComponent.cpp.s

.PHONY : src/engine/components/LightComponent.s

# target to generate assembly for a file
src/engine/components/LightComponent.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/components/LightComponent.cpp.s
.PHONY : src/engine/components/LightComponent.cpp.s

src/engine/core/Entities.o: src/engine/core/Entities.cpp.o

.PHONY : src/engine/core/Entities.o

# target to build an object file
src/engine/core/Entities.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/core/Entities.cpp.o
.PHONY : src/engine/core/Entities.cpp.o

src/engine/core/Entities.i: src/engine/core/Entities.cpp.i

.PHONY : src/engine/core/Entities.i

# target to preprocess a source file
src/engine/core/Entities.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/core/Entities.cpp.i
.PHONY : src/engine/core/Entities.cpp.i

src/engine/core/Entities.s: src/engine/core/Entities.cpp.s

.PHONY : src/engine/core/Entities.s

# target to generate assembly for a file
src/engine/core/Entities.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/core/Entities.cpp.s
.PHONY : src/engine/core/Entities.cpp.s

src/engine/core/Entity.o: src/engine/core/Entity.cpp.o

.PHONY : src/engine/core/Entity.o

# target to build an object file
src/engine/core/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/core/Entity.cpp.o
.PHONY : src/engine/core/Entity.cpp.o

src/engine/core/Entity.i: src/engine/core/Entity.cpp.i

.PHONY : src/engine/core/Entity.i

# target to preprocess a source file
src/engine/core/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/core/Entity.cpp.i
.PHONY : src/engine/core/Entity.cpp.i

src/engine/core/Entity.s: src/engine/core/Entity.cpp.s

.PHONY : src/engine/core/Entity.s

# target to generate assembly for a file
src/engine/core/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/core/Entity.cpp.s
.PHONY : src/engine/core/Entity.cpp.s

src/engine/core/EventsHandler.o: src/engine/core/EventsHandler.cpp.o

.PHONY : src/engine/core/EventsHandler.o

# target to build an object file
src/engine/core/EventsHandler.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/core/EventsHandler.cpp.o
.PHONY : src/engine/core/EventsHandler.cpp.o

src/engine/core/EventsHandler.i: src/engine/core/EventsHandler.cpp.i

.PHONY : src/engine/core/EventsHandler.i

# target to preprocess a source file
src/engine/core/EventsHandler.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/core/EventsHandler.cpp.i
.PHONY : src/engine/core/EventsHandler.cpp.i

src/engine/core/EventsHandler.s: src/engine/core/EventsHandler.cpp.s

.PHONY : src/engine/core/EventsHandler.s

# target to generate assembly for a file
src/engine/core/EventsHandler.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/core/EventsHandler.cpp.s
.PHONY : src/engine/core/EventsHandler.cpp.s

src/engine/core/Game.o: src/engine/core/Game.cpp.o

.PHONY : src/engine/core/Game.o

# target to build an object file
src/engine/core/Game.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/core/Game.cpp.o
.PHONY : src/engine/core/Game.cpp.o

src/engine/core/Game.i: src/engine/core/Game.cpp.i

.PHONY : src/engine/core/Game.i

# target to preprocess a source file
src/engine/core/Game.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/core/Game.cpp.i
.PHONY : src/engine/core/Game.cpp.i

src/engine/core/Game.s: src/engine/core/Game.cpp.s

.PHONY : src/engine/core/Game.s

# target to generate assembly for a file
src/engine/core/Game.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/core/Game.cpp.s
.PHONY : src/engine/core/Game.cpp.s

src/engine/core/Scene.o: src/engine/core/Scene.cpp.o

.PHONY : src/engine/core/Scene.o

# target to build an object file
src/engine/core/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/core/Scene.cpp.o
.PHONY : src/engine/core/Scene.cpp.o

src/engine/core/Scene.i: src/engine/core/Scene.cpp.i

.PHONY : src/engine/core/Scene.i

# target to preprocess a source file
src/engine/core/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/core/Scene.cpp.i
.PHONY : src/engine/core/Scene.cpp.i

src/engine/core/Scene.s: src/engine/core/Scene.cpp.s

.PHONY : src/engine/core/Scene.s

# target to generate assembly for a file
src/engine/core/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/core/Scene.cpp.s
.PHONY : src/engine/core/Scene.cpp.s

src/engine/exceptions/ComponentPoolException.o: src/engine/exceptions/ComponentPoolException.cpp.o

.PHONY : src/engine/exceptions/ComponentPoolException.o

# target to build an object file
src/engine/exceptions/ComponentPoolException.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/exceptions/ComponentPoolException.cpp.o
.PHONY : src/engine/exceptions/ComponentPoolException.cpp.o

src/engine/exceptions/ComponentPoolException.i: src/engine/exceptions/ComponentPoolException.cpp.i

.PHONY : src/engine/exceptions/ComponentPoolException.i

# target to preprocess a source file
src/engine/exceptions/ComponentPoolException.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/exceptions/ComponentPoolException.cpp.i
.PHONY : src/engine/exceptions/ComponentPoolException.cpp.i

src/engine/exceptions/ComponentPoolException.s: src/engine/exceptions/ComponentPoolException.cpp.s

.PHONY : src/engine/exceptions/ComponentPoolException.s

# target to generate assembly for a file
src/engine/exceptions/ComponentPoolException.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/exceptions/ComponentPoolException.cpp.s
.PHONY : src/engine/exceptions/ComponentPoolException.cpp.s

src/engine/helpers/GeometryHelper.o: src/engine/helpers/GeometryHelper.cpp.o

.PHONY : src/engine/helpers/GeometryHelper.o

# target to build an object file
src/engine/helpers/GeometryHelper.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/helpers/GeometryHelper.cpp.o
.PHONY : src/engine/helpers/GeometryHelper.cpp.o

src/engine/helpers/GeometryHelper.i: src/engine/helpers/GeometryHelper.cpp.i

.PHONY : src/engine/helpers/GeometryHelper.i

# target to preprocess a source file
src/engine/helpers/GeometryHelper.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/helpers/GeometryHelper.cpp.i
.PHONY : src/engine/helpers/GeometryHelper.cpp.i

src/engine/helpers/GeometryHelper.s: src/engine/helpers/GeometryHelper.cpp.s

.PHONY : src/engine/helpers/GeometryHelper.s

# target to generate assembly for a file
src/engine/helpers/GeometryHelper.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/helpers/GeometryHelper.cpp.s
.PHONY : src/engine/helpers/GeometryHelper.cpp.s

src/engine/network/Selector.o: src/engine/network/Selector.cpp.o

.PHONY : src/engine/network/Selector.o

# target to build an object file
src/engine/network/Selector.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/network/Selector.cpp.o
.PHONY : src/engine/network/Selector.cpp.o

src/engine/network/Selector.i: src/engine/network/Selector.cpp.i

.PHONY : src/engine/network/Selector.i

# target to preprocess a source file
src/engine/network/Selector.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/network/Selector.cpp.i
.PHONY : src/engine/network/Selector.cpp.i

src/engine/network/Selector.s: src/engine/network/Selector.cpp.s

.PHONY : src/engine/network/Selector.s

# target to generate assembly for a file
src/engine/network/Selector.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/network/Selector.cpp.s
.PHONY : src/engine/network/Selector.cpp.s

src/engine/network/Socket.o: src/engine/network/Socket.cpp.o

.PHONY : src/engine/network/Socket.o

# target to build an object file
src/engine/network/Socket.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/network/Socket.cpp.o
.PHONY : src/engine/network/Socket.cpp.o

src/engine/network/Socket.i: src/engine/network/Socket.cpp.i

.PHONY : src/engine/network/Socket.i

# target to preprocess a source file
src/engine/network/Socket.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/network/Socket.cpp.i
.PHONY : src/engine/network/Socket.cpp.i

src/engine/network/Socket.s: src/engine/network/Socket.cpp.s

.PHONY : src/engine/network/Socket.s

# target to generate assembly for a file
src/engine/network/Socket.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/network/Socket.cpp.s
.PHONY : src/engine/network/Socket.cpp.s

src/engine/systems/ClientNetworkSystem.o: src/engine/systems/ClientNetworkSystem.cpp.o

.PHONY : src/engine/systems/ClientNetworkSystem.o

# target to build an object file
src/engine/systems/ClientNetworkSystem.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/systems/ClientNetworkSystem.cpp.o
.PHONY : src/engine/systems/ClientNetworkSystem.cpp.o

src/engine/systems/ClientNetworkSystem.i: src/engine/systems/ClientNetworkSystem.cpp.i

.PHONY : src/engine/systems/ClientNetworkSystem.i

# target to preprocess a source file
src/engine/systems/ClientNetworkSystem.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/systems/ClientNetworkSystem.cpp.i
.PHONY : src/engine/systems/ClientNetworkSystem.cpp.i

src/engine/systems/ClientNetworkSystem.s: src/engine/systems/ClientNetworkSystem.cpp.s

.PHONY : src/engine/systems/ClientNetworkSystem.s

# target to generate assembly for a file
src/engine/systems/ClientNetworkSystem.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/systems/ClientNetworkSystem.cpp.s
.PHONY : src/engine/systems/ClientNetworkSystem.cpp.s

src/engine/systems/DisplaySystem.o: src/engine/systems/DisplaySystem.cpp.o

.PHONY : src/engine/systems/DisplaySystem.o

# target to build an object file
src/engine/systems/DisplaySystem.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/systems/DisplaySystem.cpp.o
.PHONY : src/engine/systems/DisplaySystem.cpp.o

src/engine/systems/DisplaySystem.i: src/engine/systems/DisplaySystem.cpp.i

.PHONY : src/engine/systems/DisplaySystem.i

# target to preprocess a source file
src/engine/systems/DisplaySystem.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/systems/DisplaySystem.cpp.i
.PHONY : src/engine/systems/DisplaySystem.cpp.i

src/engine/systems/DisplaySystem.s: src/engine/systems/DisplaySystem.cpp.s

.PHONY : src/engine/systems/DisplaySystem.s

# target to generate assembly for a file
src/engine/systems/DisplaySystem.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/systems/DisplaySystem.cpp.s
.PHONY : src/engine/systems/DisplaySystem.cpp.s

src/engine/systems/PhysicsSystem.o: src/engine/systems/PhysicsSystem.cpp.o

.PHONY : src/engine/systems/PhysicsSystem.o

# target to build an object file
src/engine/systems/PhysicsSystem.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/systems/PhysicsSystem.cpp.o
.PHONY : src/engine/systems/PhysicsSystem.cpp.o

src/engine/systems/PhysicsSystem.i: src/engine/systems/PhysicsSystem.cpp.i

.PHONY : src/engine/systems/PhysicsSystem.i

# target to preprocess a source file
src/engine/systems/PhysicsSystem.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/systems/PhysicsSystem.cpp.i
.PHONY : src/engine/systems/PhysicsSystem.cpp.i

src/engine/systems/PhysicsSystem.s: src/engine/systems/PhysicsSystem.cpp.s

.PHONY : src/engine/systems/PhysicsSystem.s

# target to generate assembly for a file
src/engine/systems/PhysicsSystem.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/systems/PhysicsSystem.cpp.s
.PHONY : src/engine/systems/PhysicsSystem.cpp.s

src/engine/systems/ServerNetworkSystem.o: src/engine/systems/ServerNetworkSystem.cpp.o

.PHONY : src/engine/systems/ServerNetworkSystem.o

# target to build an object file
src/engine/systems/ServerNetworkSystem.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/systems/ServerNetworkSystem.cpp.o
.PHONY : src/engine/systems/ServerNetworkSystem.cpp.o

src/engine/systems/ServerNetworkSystem.i: src/engine/systems/ServerNetworkSystem.cpp.i

.PHONY : src/engine/systems/ServerNetworkSystem.i

# target to preprocess a source file
src/engine/systems/ServerNetworkSystem.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/systems/ServerNetworkSystem.cpp.i
.PHONY : src/engine/systems/ServerNetworkSystem.cpp.i

src/engine/systems/ServerNetworkSystem.s: src/engine/systems/ServerNetworkSystem.cpp.s

.PHONY : src/engine/systems/ServerNetworkSystem.s

# target to generate assembly for a file
src/engine/systems/ServerNetworkSystem.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/systems/ServerNetworkSystem.cpp.s
.PHONY : src/engine/systems/ServerNetworkSystem.cpp.s

src/engine/systems/System.o: src/engine/systems/System.cpp.o

.PHONY : src/engine/systems/System.o

# target to build an object file
src/engine/systems/System.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/systems/System.cpp.o
.PHONY : src/engine/systems/System.cpp.o

src/engine/systems/System.i: src/engine/systems/System.cpp.i

.PHONY : src/engine/systems/System.i

# target to preprocess a source file
src/engine/systems/System.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/systems/System.cpp.i
.PHONY : src/engine/systems/System.cpp.i

src/engine/systems/System.s: src/engine/systems/System.cpp.s

.PHONY : src/engine/systems/System.s

# target to generate assembly for a file
src/engine/systems/System.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/systems/System.cpp.s
.PHONY : src/engine/systems/System.cpp.s

src/engine/utils/EntityComparator.o: src/engine/utils/EntityComparator.cpp.o

.PHONY : src/engine/utils/EntityComparator.o

# target to build an object file
src/engine/utils/EntityComparator.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/utils/EntityComparator.cpp.o
.PHONY : src/engine/utils/EntityComparator.cpp.o

src/engine/utils/EntityComparator.i: src/engine/utils/EntityComparator.cpp.i

.PHONY : src/engine/utils/EntityComparator.i

# target to preprocess a source file
src/engine/utils/EntityComparator.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/utils/EntityComparator.cpp.i
.PHONY : src/engine/utils/EntityComparator.cpp.i

src/engine/utils/EntityComparator.s: src/engine/utils/EntityComparator.cpp.s

.PHONY : src/engine/utils/EntityComparator.s

# target to generate assembly for a file
src/engine/utils/EntityComparator.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/utils/EntityComparator.cpp.s
.PHONY : src/engine/utils/EntityComparator.cpp.s

src/engine/utils/TagComparator.o: src/engine/utils/TagComparator.cpp.o

.PHONY : src/engine/utils/TagComparator.o

# target to build an object file
src/engine/utils/TagComparator.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/utils/TagComparator.cpp.o
.PHONY : src/engine/utils/TagComparator.cpp.o

src/engine/utils/TagComparator.i: src/engine/utils/TagComparator.cpp.i

.PHONY : src/engine/utils/TagComparator.i

# target to preprocess a source file
src/engine/utils/TagComparator.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/utils/TagComparator.cpp.i
.PHONY : src/engine/utils/TagComparator.cpp.i

src/engine/utils/TagComparator.s: src/engine/utils/TagComparator.cpp.s

.PHONY : src/engine/utils/TagComparator.s

# target to generate assembly for a file
src/engine/utils/TagComparator.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/utils/TagComparator.cpp.s
.PHONY : src/engine/utils/TagComparator.cpp.s

src/server.o: src/server.cpp.o

.PHONY : src/server.o

# target to build an object file
src/server.cpp.o:
	$(MAKE) -f CMakeFiles/worms-server.dir/build.make CMakeFiles/worms-server.dir/src/server.cpp.o
.PHONY : src/server.cpp.o

src/server.i: src/server.cpp.i

.PHONY : src/server.i

# target to preprocess a source file
src/server.cpp.i:
	$(MAKE) -f CMakeFiles/worms-server.dir/build.make CMakeFiles/worms-server.dir/src/server.cpp.i
.PHONY : src/server.cpp.i

src/server.s: src/server.cpp.s

.PHONY : src/server.s

# target to generate assembly for a file
src/server.cpp.s:
	$(MAKE) -f CMakeFiles/worms-server.dir/build.make CMakeFiles/worms-server.dir/src/server.cpp.s
.PHONY : src/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... engine"
	@echo "... worms"
	@echo "... rebuild_cache"
	@echo "... worms-server"
	@echo "... tests-engine"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/engine/components/CameraComponent.o"
	@echo "... src/engine/components/CameraComponent.i"
	@echo "... src/engine/components/CameraComponent.s"
	@echo "... src/engine/components/ComponentPoolEvent.o"
	@echo "... src/engine/components/ComponentPoolEvent.i"
	@echo "... src/engine/components/ComponentPoolEvent.s"
	@echo "... src/engine/components/HitboxComponent.o"
	@echo "... src/engine/components/HitboxComponent.i"
	@echo "... src/engine/components/HitboxComponent.s"
	@echo "... src/engine/components/IrrlichtComponent.o"
	@echo "... src/engine/components/IrrlichtComponent.i"
	@echo "... src/engine/components/IrrlichtComponent.s"
	@echo "... src/engine/components/LightComponent.o"
	@echo "... src/engine/components/LightComponent.i"
	@echo "... src/engine/components/LightComponent.s"
	@echo "... src/engine/core/Entities.o"
	@echo "... src/engine/core/Entities.i"
	@echo "... src/engine/core/Entities.s"
	@echo "... src/engine/core/Entity.o"
	@echo "... src/engine/core/Entity.i"
	@echo "... src/engine/core/Entity.s"
	@echo "... src/engine/core/EventsHandler.o"
	@echo "... src/engine/core/EventsHandler.i"
	@echo "... src/engine/core/EventsHandler.s"
	@echo "... src/engine/core/Game.o"
	@echo "... src/engine/core/Game.i"
	@echo "... src/engine/core/Game.s"
	@echo "... src/engine/core/Scene.o"
	@echo "... src/engine/core/Scene.i"
	@echo "... src/engine/core/Scene.s"
	@echo "... src/engine/exceptions/ComponentPoolException.o"
	@echo "... src/engine/exceptions/ComponentPoolException.i"
	@echo "... src/engine/exceptions/ComponentPoolException.s"
	@echo "... src/engine/helpers/GeometryHelper.o"
	@echo "... src/engine/helpers/GeometryHelper.i"
	@echo "... src/engine/helpers/GeometryHelper.s"
	@echo "... src/engine/network/Selector.o"
	@echo "... src/engine/network/Selector.i"
	@echo "... src/engine/network/Selector.s"
	@echo "... src/engine/network/Socket.o"
	@echo "... src/engine/network/Socket.i"
	@echo "... src/engine/network/Socket.s"
	@echo "... src/engine/systems/ClientNetworkSystem.o"
	@echo "... src/engine/systems/ClientNetworkSystem.i"
	@echo "... src/engine/systems/ClientNetworkSystem.s"
	@echo "... src/engine/systems/DisplaySystem.o"
	@echo "... src/engine/systems/DisplaySystem.i"
	@echo "... src/engine/systems/DisplaySystem.s"
	@echo "... src/engine/systems/PhysicsSystem.o"
	@echo "... src/engine/systems/PhysicsSystem.i"
	@echo "... src/engine/systems/PhysicsSystem.s"
	@echo "... src/engine/systems/ServerNetworkSystem.o"
	@echo "... src/engine/systems/ServerNetworkSystem.i"
	@echo "... src/engine/systems/ServerNetworkSystem.s"
	@echo "... src/engine/systems/System.o"
	@echo "... src/engine/systems/System.i"
	@echo "... src/engine/systems/System.s"
	@echo "... src/engine/utils/EntityComparator.o"
	@echo "... src/engine/utils/EntityComparator.i"
	@echo "... src/engine/utils/EntityComparator.s"
	@echo "... src/engine/utils/TagComparator.o"
	@echo "... src/engine/utils/TagComparator.i"
	@echo "... src/engine/utils/TagComparator.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

